spring:
  datasource:
    username: root
    password: sail
    url: jdbc:mysql://localhost:3306/order
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.abc.ecommerce.kafka.OrderConfirmation


server:
  port: 8092
  
application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/product
    payment-url: http://localhost:8222/api/v1/payments