spring:
  datasource:
    username: root
    password: sail
    url: jdbc:mysql://localhost:3306/payment
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:  paymentConfirmation:com.abc.ecommerce.notification.PaymentNotificationRequest


server:
  port: 8093