spring:
  datasource:
    username: root
    password: sail
    url: jdbc:mysql://localhost:3306/product
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true

server:
  port: 8091